# SITE SETUP
# Documentation: https://sourcethemes.com/academic/

# Choose a theme.
#   Latest themes (may require updating): https://sourcethemes.com/academic/themes/
#   Browse built-in themes in `themes/academic/data/themes/`
#   Browse user installed themes in `data/themes/`
theme = "minimal"

# Enable users to switch between day and night mode?
day_night = true

# Override the theme's font set (optional).
#   Latest font sets (may require updating): https://sourcethemes.com/academic/themes/
#   Browse built-in font sets in `themes/academic/data/fonts/`
#   Browse user installed font sets in `data/fonts/`
font = ""

# Choose a font size.
# Sizes: XS (extra small), S (small), M (medium), L (large - DEFAULT), XL (extra large)
font_size = "L"

############################
## Basic Info
############################

# Website type
#   Improve how search engines understand your site.
#   For personal sites, choose "Person".
#   For organizations and projects, choose from https://schema.org/Organization#subtypes
#   E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization
site_type = "EducationalOrganization"

# Local business type (optional)
# If you entered "LocalBusiness" above, choose the type of business from https://schema.org/LocalBusiness#subtypes
local_business_type = ""

# Organization name (optional)
# Enter an organization or project name. Defaults to the site title from `config.toml`.
org_name = "University of Chicago"

# Description for social sharing and search engines. If undefined, superuser role is used in place.
description = "Introductory course to reproducible research and programming in the social sciences."

# Default image for social sharing and search engines. Place image in `static/img/` folder and specify image name here.
sharing_image = ""

# Twitter username (without @). Used when a vistor shares your site on Twitter.
twitter = ""

# Enable global source code highlighting? true/false
# Documentation: https://sourcethemes.com/academic/docs/writing-markdown-latex/#highlighting-options
highlight = true
highlight_languages = ["r"]  # Add support for highlighting additional languages
highlight_style = "magula"  # For supported styles, see https://cdnjs.com/libraries/highlight.js/

# Enable global LaTeX math rendering?
#   If false, you can enable it locally on a per page basis.
math = true

# Privacy pack
#   Show a cookie consent message to visitors
#   Anonymize IP in Google Analytics (if enabled)
privacy_pack = true

# Date and time format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
#   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
date_format = "Jan 2, 2006"
#   Examples: "3:04 pm" or "15:04"
time_format = "3:04 PM"
# Address format (choose from the [address_formats] list below or add you own to the list).
address_format = "en-us"

# Available address formats.
[address_formats]
  en-us = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ' ', '']}
  en-gb = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ', ', '']}
  zh = {order = ['postcode', 'region', 'city', 'street'], delimiters = [' ', ' ', ' ', '']}

############################
## Contact Widget setup   ##
############################

# Enter contact details (optional). To hide a field, clear it to "".
email = "soltoffbc@uchicago.edu"
phone = "773-702-9360"
address = {street = "1155 E. 60th St.", city = "Chicago", region = "IL", postcode = "60637", country = "United States", country_code = "US"}
coordinates = {latitude = "41.790201", longitude = "-87.596059"}

# Office hours: use `<br>` to insert a line break, or set to "" to remove office hours
office_hours = ["Monday 10:00am to 12:00pm"]

# Enter an optional link for booking appointments (e.g. calendly.com).
# appointment_url = "https://calendly.com"

# Contact links
#   Set to `[]` to disable, or comment out unwanted lines with a hash `#`.
contact_links = [
  {icon = "linkedin", icon_pack = "fab", name = "Connect with me", link = "https://www.linkedin.com/in/benjaminsoltoff/"},
  {icon = "github", icon_pack = "fab", name = "View my contributions", link = "https://github.com/bensoltoff"}
  ]

[map]
  # To show your address on a map in the Contact widget, enter your latitude and longitude (above)
  # and choose a map provider below.
  #
  # To use Google Maps, set `engine` to 1 and enter your API key that can be obtained here:
  #   https://developers.google.com/maps/documentation/javascript/get-api-key
  # To use OpenStreetMap tiles, set `engine` to 2.
  # To use OpenStreetMap on a high traffic site, set `engine` to 3 and enter your API key that can be obtained here:
  #   https://www.mapbox.com/studio/account/tokens
  #
  # Map provider:
  #   0: No map
  #   1: Google Maps
  #   2: OpenStreetMap (Mapnik)
  #   3: OpenStreetMap (Mapbox)
  engine = 2
  api_key = ""
  zoom = 15

############################
## Plugins                ##
############################

# Load CSS and JS plugins
#   E.g. To load `/assets/css/custom.css`, set `plugins_css = ["custom"]`.
#   E.g. To load `/assets/js/custom.js`, set `plugins_js = ["custom"]`.
plugins_css = []
plugins_js  = ["math-code"]

############################
## Advanced options       ##
############################

# Get user avatars from Gravatar.com? (true/false)
gravatar = false

# Main menu alignment (l = left, c = center, r = right) and logo options.
main_menu = {align = "l", show_logo = true}

# Show estimated reading time for posts? (true/false)
reading_time = true

# Display comment count (if commenting enabled in config.toml)? (true/false)
comment_count = true

# Display next/previous section pager? (true/false)
section_pager = false
docs_section_pager = true  # Display pager in Docs layout (e.g. tutorials)?

# Enable in-built social sharing buttons? (true/false)
sharing = true

# Link authors to their profile page? (true/false)
link_authors = true

# Configuration of publication pages.
[publications]
  # Date format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "January 2006"

  # Citation style ("apa" or "mla")
  citation_style = "apa"

# Configuration of project pages.
[projects]
  # Views for associated content.
  #   1: List
  #   2: Compact
  #   3: Card
  #   4: Citation (publications only)
  post_view = 2
  publication_view = 2
  talk_view = 2

# Search.
[search]
  # Search provider:
  #   0: No search engine
  #   1: Academic (built-in)
  #   2: Algolia (https://www.algolia.com)
  engine = 1

  # Configuration of Algolia search engine.
  # Paste the values from your Algolia dashboard.
  [search.algolia]
    app_id = ""
    api_key = ""
    index_name = ""
    show_logo = false

# Comments.
[comments]
  # Comment provider:
  #   0: Disabled
  #   1: Disqus (https://disqus.com)
  #   2: Commento (https://commento.io)
  engine = 0

  # Which page types are commentable?
  commentable = {page = true, post = true, docs = true}

  # Configuration of Disqus.
  [comments.disqus]
    shortname = ""  # Paste the shortname from your Disqus dashboard.
    show_count = true  # Show comment count in page header? (true/false)

############################
## Marketing
############################
[marketing]
  google_analytics = "UA-45631879-2"
  google_tag_manager = ""
